version: 0.0
os: linux
files:
  - source: /api
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 100
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 100
      runas: root
